import { Category, Term } from './types';

// Updated to "Tech/Neon" style with transparent backgrounds and glowing borders
export const CATEGORY_COLORS: Record<Category, string> = {
  [Category.GENERAL]: 'bg-gray-500/10 text-gray-300 border-gray-500/50',
  [Category.ALJ_SPECIALIZED]: 'bg-blue-500/10 text-blue-300 border-blue-500/50',
  [Category.TOYOTA_TERMS]: 'bg-red-500/10 text-red-300 border-red-500/50',
  [Category.OTHER]: 'bg-purple-500/10 text-purple-300 border-purple-500/50',
  [Category.RESIN_MOLDING]: 'bg-yellow-500/10 text-yellow-300 border-yellow-500/50',
  [Category.RESIN_MOLD]: 'bg-orange-500/10 text-orange-300 border-orange-500/50',
  [Category.DESIGN_SPECIALIZED]: 'bg-emerald-500/10 text-emerald-300 border-emerald-500/50',
};

export const CATEGORY_LABELS: Record<string, Record<string, string>> = {
  '一般': { ENG: 'General', JP: '一般', MN: 'Ерөнхий' },
  'ALJ専門': { ENG: 'ALJ Specialized', JP: 'ALJ専門', MN: 'ALJ Тусгай' },
  'トヨタ用語': { ENG: 'Toyota Terms', JP: 'トヨタ用語', MN: 'Toyota Нэршил' },
  'その他': { ENG: 'Other', JP: 'その他', MN: 'Бусад' },
  '樹脂成型': { ENG: 'Resin Molding', JP: '樹脂成型', MN: 'Хуванцар цутгалт' },
  '樹脂金型': { ENG: 'Resin Mold', JP: '樹脂金型', MN: 'Хуванцар хэв' },
  '設計専門': { ENG: 'Design Specialized', JP: '設計専門', MN: 'Зураг төсөл' },
};

export const TRANSLATIONS = {
  ENG: {
    SYSTEM_ONLINE: "SYS: ONLINE",
    SLOGAN: "人がつくる。夢につながる",
    LATENCY: "LATENCY",
    DB_RECORDS: "DB_RECORDS",
    CREATED_BY: "created by BAYARU",
    SEARCH_PLACEHOLDER: "FILTER_TERMS...",
    RESULTS: "Results",
    SORT: "Sort: DESC",
    NO_DATA: "NO DATA FOUND",
    DEFINITION: "Definition",
    ALIASES: "Aliases / Related",
    MEDIA_GALLERY: "MEDIA_GALLERY_MODULE",
    NO_MEDIA: "No Media Assets Attached",
    METADATA: "Metadata",
    ID: "ID",
    AUTHOR: "Author",
    CREATED: "Created",
    ACCESS: "Access",
    GRANTED: "Granted",
    MODIFICATION_LOG: "Modification Log",
    EDIT_RECORD: "Edit Record",
    DELETE_RECORD: "Delete Record",
    CONFIRM_DELETE: "CONFIRM DELETION: Are you sure you want to remove this data node?",
    NEW_ENTRY: "NEW_TERM",
    EDIT_ENTRY: "EDIT_SEQUENCE",
    TERM_JP: "Term (Japanese)",
    READING: "Reading (Furigana)",
    TERM_EN: "English Term",
    MEANING: "Definition / Meaning",
    CATEGORY: "Categories (Select Multiple)",
    ALIAS: "Alias (Optional)",
    IMAGE_URL: "Image URL",
    OPERATOR_NAME: "AUTHOR NAME",
    SAVE: "Sign & Save",
    CANCEL: "Cancel",
    ADD_ENTRY: "Add Data Entry",
    DATA_CATEGORIES: "Data Categories",
    SYSTEM_LANGUAGE: "System Language",
    SELECT_NODE: "SELECT A DATA NODE TO INSPECT",
    WAITING_INPUT: "Waiting for user input...",
    CONFIDENTIAL: "CONFIDENTIAL",
    REFERENCE_IMAGE: "Reference_Image",
    ENTER_NAME: "Enter your name to sign this record",
    ALL_SYSTEMS: "ALL SYSTEMS",
    GLOSSARY_TITLE: "autoliv_GLOSSARY",
    EXAMPLE: "e.g.",
    UPLOAD_IMAGE: "Upload Image",
    OR_ENTER_URL: "or enter URL",
    REMOVE_IMAGE: "Remove Image"
  },
  JP: {
    SYSTEM_ONLINE: "システム: オンライン",
    SLOGAN: "人がつくる。夢につながる",
    LATENCY: "レイテンシ",
    DB_RECORDS: "DBレコード",
    CREATED_BY: "作成者: BAYARU",
    SEARCH_PLACEHOLDER: "用語を検索...",
    RESULTS: "結果",
    SORT: "ソート: 降順",
    NO_DATA: "データが見つかりません",
    DEFINITION: "定義",
    ALIASES: "別名 / 関連",
    MEDIA_GALLERY: "メディアギャラリー",
    NO_MEDIA: "メディア資産なし",
    METADATA: "メタデータ",
    ID: "ID",
    AUTHOR: "作成者",
    CREATED: "作成日",
    ACCESS: "アクセス",
    GRANTED: "許可済",
    MODIFICATION_LOG: "変更履歴",
    EDIT_RECORD: "レコード編集",
    DELETE_RECORD: "レコード削除",
    CONFIRM_DELETE: "削除確認: このデータノードを削除してもよろしいですか？",
    NEW_ENTRY: "新規用語",
    EDIT_ENTRY: "編集シーケンス",
    TERM_JP: "用語 (日本語)",
    READING: "読み方 (フリガナ)",
    TERM_EN: "英語用語",
    MEANING: "定義 / 意味",
    CATEGORY: "カテゴリ (複数選択可)",
    ALIAS: "別名 (任意)",
    IMAGE_URL: "画像URL",
    OPERATOR_NAME: "作成者名",
    SAVE: "署名して保存",
    CANCEL: "キャンセル",
    ADD_ENTRY: "データエントリ追加",
    DATA_CATEGORIES: "データカテゴリ",
    SYSTEM_LANGUAGE: "システム言語",
    SELECT_NODE: "検査するデータノードを選択",
    WAITING_INPUT: "ユーザー入力待ち...",
    CONFIDENTIAL: "機密",
    REFERENCE_IMAGE: "参照画像",
    ENTER_NAME: "このレコードに署名するための名前を入力",
    ALL_SYSTEMS: "全システム",
    GLOSSARY_TITLE: "autoliv用語集",
    EXAMPLE: "例",
    UPLOAD_IMAGE: "画像をアップロード",
    OR_ENTER_URL: "またはURLを入力",
    REMOVE_IMAGE: "画像を削除"
  },
  MN: {
    SYSTEM_ONLINE: "СИСТЕМ: ONLINE",
    SLOGAN: "人がつくる。夢につながる",
    LATENCY: "ХУРД",
    DB_RECORDS: "ӨГӨГДӨЛ",
    CREATED_BY: "created by BAYARU",
    SEARCH_PLACEHOLDER: "ХАЙХ...",
    RESULTS: "Илэрц",
    SORT: "Эрэмбэ",
    NO_DATA: "ӨГӨГДӨЛ ОЛДСОНГҮЙ",
    DEFINITION: "Тайлбар",
    ALIASES: "Бусад нэршил / Холбоотой",
    MEDIA_GALLERY: "МЕДИА САН",
    NO_MEDIA: "Медиа файл алга",
    METADATA: "Метадата",
    ID: "ID",
    AUTHOR: "Үүсгэсэн",
    CREATED: "Огноо",
    ACCESS: "Хандалт",
    GRANTED: "Зөвшөөрсөн",
    MODIFICATION_LOG: "Өөрчлөлтийн түүх",
    EDIT_RECORD: "Засах",
    DELETE_RECORD: "Устгах",
    CONFIRM_DELETE: "УСТГАХЫГ БАТАЛГААЖУУЛАХ: Та энэ өгөгдлийг устгахдаа итгэлтэй байна уу?",
    NEW_ENTRY: "ШИНЭ НЭР ТОМЬЁО",
    EDIT_ENTRY: "ЗАСВАРЛАХ",
    TERM_JP: "Нэр томьёо (Япон)",
    READING: "Уншлага (Фүригана)",
    TERM_EN: "Англи нэршил",
    MEANING: "Тайлбар / Утга",
    CATEGORY: "Ангилал (Олон сонголттой)",
    ALIAS: "Бусад нэршил (Заавал биш)",
    IMAGE_URL: "Зургийн холбоос",
    OPERATOR_NAME: "ЗОХИОГЧИЙН НЭР",
    SAVE: "Хадгалах",
    CANCEL: "Болих",
    ADD_ENTRY: "Мэдээлэл нэмэх",
    DATA_CATEGORIES: "Өгөгдлийн ангилал",
    SYSTEM_LANGUAGE: "Системийн хэл",
    SELECT_NODE: "ХАРАХ ӨГӨГДЛӨӨ СОНГОНО УУ",
    WAITING_INPUT: "Хүлээж байна...",
    CONFIDENTIAL: "НУУЦ",
    REFERENCE_IMAGE: "Лавлах зураг",
    ENTER_NAME: "Нэрээ оруулна уу",
    ALL_SYSTEMS: "БҮХ СИСТЕМ",
    GLOSSARY_TITLE: "autoliv ТОЛЬ",
    EXAMPLE: "Жш.",
    UPLOAD_IMAGE: "Зураг оруулах",
    OR_ENTER_URL: "эсвэл URL оруулах",
    REMOVE_IMAGE: "Зураг устгах"
  }
};

export const MOCK_TERMS: Term[] = [
  {
    id: 1,
    term: "射出成形",
    reading: "しゃしゅつせいけい",
    alias: "インジェクション",
    english: "Injection Molding",
    meaning: "加熱して溶かしたプラスチック材料を金型の中に圧力をかけて注入し、冷却・固化させて成形品を作る方法。",
    categories: [Category.RESIN_MOLDING, Category.GENERAL],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Injection_moulding.png/800px-Injection_moulding.png",
    createdBy: "Admin",
    createdAt: "2023-01-10",
    history: []
  },
  {
    id: 2,
    term: "アンドン",
    reading: "あんどん",
    english: "Andon",
    meaning: "生産ラインで異常が発生した際に、作業者が点灯させて管理者や周囲に知らせる表示灯のこと。トヨタ生産方式の重要な要素。",
    categories: [Category.TOYOTA_TERMS, Category.ALJ_SPECIALIZED],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/93/Andon-light.jpg",
    createdBy: "Manager A",
    createdAt: "2023-02-15",
    history: [{ editedBy: "Supervisor B", editedAt: "2023-03-01" }]
  },
  {
    id: 3,
    term: "公差",
    reading: "こうさ",
    english: "Tolerance",
    meaning: "図面上で指定された寸法の許容される誤差の範囲。最大許容寸法と最小許容寸法の差。",
    categories: [Category.DESIGN_SPECIALIZED, Category.GENERAL],
    createdBy: "Engineer K",
    createdAt: "2023-05-20",
    history: []
  },
  {
    id: 4,
    term: "キャビティ",
    reading: "きゃびてぃ",
    alias: "メス型",
    english: "Cavity",
    meaning: "金型において、成形品の外観となる面を形成する凹形状の部分。通常は固定側に配置される。",
    categories: [Category.RESIN_MOLD],
    createdBy: "System",
    createdAt: "2023-01-01",
    history: []
  },
  {
    id: 5,
    term: "コア",
    reading: "こあ",
    alias: "オス型",
    english: "Core",
    meaning: "金型において、成形品の内面を形成する凸形状の部分。通常は可動側に配置される。",
    categories: [Category.RESIN_MOLD],
    createdBy: "System",
    createdAt: "2023-01-01",
    history: []
  },
  {
    id: 6,
    term: "カイゼン",
    reading: "かいぜん",
    english: "Kaizen / Continuous Improvement",
    meaning: "作業の効率化や安全性の向上、品質改善などを目的として、継続的に業務を見直し変更していく活動。",
    categories: [Category.TOYOTA_TERMS, Category.GENERAL],
    createdBy: "System",
    createdAt: "2023-01-01",
    history: []
  },
  {
    id: 7,
    term: "バリ",
    reading: "ばり",
    english: "Burr / Flash",
    meaning: "加工時や成形時に、材料が金型の隙間にはみ出して固まった余分な部分。",
    categories: [Category.RESIN_MOLDING, Category.GENERAL],
    createdBy: "System",
    createdAt: "2023-01-01",
    history: []
  },
  {
    id: 8,
    term: "ジャストインタイム",
    reading: "じゃすといんたいむ",
    alias: "JIT",
    english: "Just In Time",
    meaning: "「必要なものを、必要な時に、必要なだけ」生産・供給し、在庫を極限まで減らす生産方式。",
    categories: [Category.TOYOTA_TERMS],
    createdBy: "System",
    createdAt: "2023-01-01",
    history: []
  },
  {
    id: 9,
    term: "PL面",
    reading: "ぱーてぃんぐらいん",
    alias: "PL",
    english: "Parting Line",
    meaning: "金型の固定側と可動側が合わさる分割面のこと。",
    categories: [Category.RESIN_MOLD, Category.DESIGN_SPECIALIZED],
    createdBy: "System",
    createdAt: "2023-01-01",
    history: []
  },
  {
    id: 10,
    term: "ショートショット",
    reading: "しょーとしょっと",
    english: "Short Shot",
    meaning: "成形材料が金型の隅々まで行き渡らず、成形品の一部が欠けてしまう不良現象。",
    categories: [Category.RESIN_MOLDING],
    createdBy: "System",
    createdAt: "2023-01-01",
    history: []
  },
  {
    id: 11,
    term: "CAD",
    reading: "きゃど",
    english: "Computer Aided Design",
    meaning: "コンピュータを用いて設計や製図を行うシステム。",
    categories: [Category.DESIGN_SPECIALIZED],
    createdBy: "System",
    createdAt: "2023-01-01",
    history: []
  },
  {
    id: 12,
    term: "ブシュ",
    reading: "ぶしゅ",
    english: "Bushing",
    meaning: "軸の回転や往復運動を支える滑り軸受の一種。または位置決めのための筒状部品。",
    categories: [Category.GENERAL, Category.RESIN_MOLD],
    createdBy: "System",
    createdAt: "2023-01-01",
    history: []
  },
  {
    id: 13,
    term: "5S",
    reading: "ごえす",
    english: "5S",
    meaning: "整理・整頓・清掃・清潔・躾の5つの頭文字をとった職場環境維持・改善のスローガン。",
    categories: [Category.GENERAL, Category.TOYOTA_TERMS],
    createdBy: "System",
    createdAt: "2023-01-01",
    history: []
  },
  {
    id: 14,
    term: "抜き勾配",
    reading: "ぬきこうばい",
    alias: "ドラフト",
    english: "Draft Angle",
    meaning: "成形品を金型から取り出しやすくするために、側面に設ける傾斜のこと。",
    categories: [Category.RESIN_MOLDING, Category.DESIGN_SPECIALIZED],
    createdBy: "System",
    createdAt: "2023-01-01",
    history: []
  },
  {
    id: 15,
    term: "ポカヨケ",
    reading: "ぽかよけ",
    english: "Poka-yoke / Mistake-proofing",
    meaning: "作業ミス（ポカ）を物理的に回避する（ヨケる）仕組みや装置。",
    categories: [Category.ALJ_SPECIALIZED, Category.TOYOTA_TERMS],
    createdBy: "System",
    createdAt: "2023-01-01",
    history: []
  }
];